services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: to-do_list
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taskflow-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-db
      PMA_USER: admin
      PMA_PASSWORD: admin
    ports:
      - "8081:80"
    networks:
      - taskflow-network

volumes:
  mysql_data:

networks:
  taskflow-network:
    driver: bridge
