version: '3.8'

services:

  app:
    build: .
    container_name: php-app-docker
    ports:
      - "8000:80" 
    volumes:
      - ./public:/var/www/html
    depends_on:
      - mysql-db
    networks:
      - taskflow-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-docker
    restart: always
    environment:
      DB_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: to-do_list
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: "America/Sao_Paulo"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taskflow-network

volumes:
  mysql_data:

networks:
  taskflow-network:
